### ISSUE TITLE
Different result on extracting tarball

### ISSUE THREAD

**Issue by willysr** [aclemons/sbo-bot#784]
please take a look on gem submission on ARCHIVE
I ran sbo-bot and it got pushed to https://github.com/SlackBuildsOrg/slackbuilds/pull/8742
it shows that no rc.gem exists, but when i look into the tarball in ARCHIVE, it does exists

```
willysr@home:~$ tar xvf /data/repo/sbo/ARCHIVE/gem.tar.gz 
gem/
gem/gem.info
gem/gem.8
gem/gem.SlackBuild
gem/doinst.sh
gem/README
gem/slack-desc
gem/rc.gem
```

**Comment by aclemons** [comment]
We could change it to force add everything and ignore the gitignore. Then if there is some rubbish, we'd just need to update the PR while reviewing.

Should we make that change?

**Comment by willysr** [comment]
ah, didn't think of that
i think i was the one who added that entry in gitignore
since there's only 1 entry who had issue, i think we can change the name of the rc.gem into something else to avoid the .gitignore entry
